### ISSUE TITLE
yugioh ppsspp stuck (corrupt save) 

### ISSUE THREAD

**Issue by sum2012** [sum2012/ppsspp-problem#52]
ONLY TALK IN HERE
@kluzzz maybe my iso have some problem because I didn't touch ppsspp a long time.
Can you tell me where do you download your iso (yugioh  1) ?

**Comment by kluzzz** [comment]
From emuparadise sum. Here the link if u want.
https://m.emuparadise.me/PSP_ISOs/Yu-Gi-Oh!_GX_Tag_Force_(USA)/156672

Hey, its ok with u? Sorry i've been bothering ur time to try fix this hehe

@kluzzz <https://github.com/kluzzz> maybe my iso have some problem because
I didn't touch ppsspp a long time.
Can you tell me where do you download your iso (yugioh 1) ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sum2012/ppsspp-problem/issues/52>, or mute the thread

**Comment by sum2012** [comment]
Thanks,I will say there "I re-dump my iso,now it work"

**Comment by kluzzz** [comment]
Ok hahaha wish u can fix my problem bro tell me when done best of luck.
Pada 9 Nov 2017 21:28, "sum" <notifications@github.com> menulis:
